version: '3.3'

volumes:
  pg_data:
  media:
  backend_static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
  backend:
    image: alextriano/foodgram_backend
    env_file: .env
    volumes:
      - backend_static:/backend_static
      - media:/app/media
    depends_on:
      - db
    restart: on-failure
  frontend:
    image: alextriano/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  nginx:
    image: alextriano/foodgram_gateway
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media:/app/media
      - backend_static:/var/html/